# -*- coding: utf-8 -*-
"""modelling_tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YUW8p3_E6lVIM2tdU0a_3Xc7vGgDLeVd

#**Modelling Tuning**

(Skilled/Advanced)

Pada tahap ini, saya membangun model machine learning menggunakan dataset yang telah melalui preprocessing (heart_preprocessing.csv).

Tujuan ddari proses ini adalah untuk melakukan hyperparameter tuning pada model Random Forest untuk mendapatkan model terbaik, serta melakukan manual logging ke MLflow Tracking UI untuk mencatat metrics dan artifak.

Setelah mencoba logging ke MLflow, saya juga mencoba untuk logging ke Dagshub UI dan membuat 2 artifak tambahan sesuai kriteria yang ditentukan.

##1. Install Library MLflow dan Dagshub
"""


"""##2. Import Library"""

import pandas as pd
import mlflow
import dagshub
import mlflow.sklearn
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.metrics import roc_curve, auc
from sklearn.inspection import permutation_importance

"""##3. Memuat Dataset"""

# Memastikan heart_preprocessing.csv Sudah Diupload ke Colab
from google.colab import files

# Upload File Jika Belum Ada
uploaded = files.upload()

df = pd.read_csv("heart_preprocessing.csv")
df.head()

"""##4. Split Data"""

X = df.drop("target", axis=1)
y = df["target"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""##5. Mendefinisikan Hyperparameter Tuning"""

# GridSearch untuk Hyperparameter Tuning
param_grid = {
    "n_estimators": [50, 100],
    "max_depth": [3, 5, None],
    "min_samples_split": [2, 5]
}

grid = GridSearchCV(
    estimator=RandomForestClassifier(random_state=42),
    param_grid=param_grid,
    cv=3,
    scoring="accuracy"
)

"""##6. Manual MLflow Logging"""

#Mulai Manual Logging di MLflow
with mlflow.start_run():

    # Fit Model
    grid.fit(X_train, y_train)
    best_model = grid.best_estimator_

    # Log Hyperparameters Manual
    mlflow.log_params(grid.best_params_)

    # Prediksi dan Log Metrics
    y_pred = best_model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    mlflow.log_metric("accuracy", acc)

    # Artifak tambahan: Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(6,4))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
    plt.title("Confusion Matrix")
    plt.savefig("confusion_matrix.png")
    mlflow.log_artifact("confusion_matrix.png")

    # Log Model Manual
    mlflow.sklearn.log_model(best_model, "model")

#Menjalankan MLflow UI


#Mengecek Apakah port 5000 Terbuka atau Tidak


#Install pyngrok


from pyngrok import ngrok

# Set auth token
ngrok.set_auth_token("37CRa3XYVY587gwuixSl6TeBJM6_7pEVsU9DSYmS4erqJUMSa")

# Jalankan MLflow UI jika belum


# Buat tunnel baru
public_url = ngrok.connect(5000, host_header="127.0.0.1")
print("MLflow UI bisa diakses di:", public_url)

"""##7. Log ke Dagshub dan Artifak Tambahan"""

# Inisialisasi DagsHub
dagshub.init(repo_owner='putriiantarii', repo_name='SMSML_Ni-Putu-Putri-Ayu-Antari', mlflow=True)

#ROC Curve
y_proba = best_model.predict_proba(X_test)[:, 1]
fpr, tpr, thresholds = roc_curve(y_test, y_proba)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, color='darkorange', lw=2, label='ROC curve (area = %0.2f)' % roc_auc)
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic')
plt.legend(loc="lower right")
plt.savefig("roc_curve.png")
plt.close()

#Feature Importance
result = permutation_importance(best_model, X_test, y_test, n_repeats=10, random_state=42)
importances = result.importances_mean
np.savetxt("feature_importance.txt", importances)

# Logging ke Dagshub
with mlflow.start_run(run_name="RandomForest_Advanced"):
    mlflow.log_params(grid.best_params_)
    mlflow.log_metric("accuracy", accuracy_score(y_test, y_pred))
    mlflow.log_metric("roc_auc", roc_auc)

    # Log Artifak Tambahan
    mlflow.log_artifact("roc_curve.png")
    mlflow.log_artifact("feature_importance.txt")

    # Log Model
    mlflow.sklearn.log_model(best_model, "model")

print("Logging ke DagsHub selesai.")

"""##8. Membuat File requirements.txt"""



"""##9. Membuat File DagsHub.txt"""

#Membuat File Dagshub.txt Berisi Tautan Menuju Repository
with open("DagsHub.txt", "w") as f:
    f.write("Experiment Advanced MLflow di DagsHub:\n")
    f.write("https://dagshub.com/putriiantarii/SMSML_Ni-Putu-Putri-Ayu-Antari.mlflow/#/experiments/0\n")
    f.write("Run RandomForest_Advanced:\n")
    f.write("https://dagshub.com/putriiantarii/SMSML_Ni-Putu-Putri-Ayu-Antari.mlflow/#/experiments/0/runs/3024e5c365f34b21be843f9c73e3a5ae\n")
